from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ramz_ild(object):
    def setupUi(self, Ramz_ild):
        Ramz_ild.setObjectName("Ramz_ild")
        Ramz_ild.resize(607, 240)
        Ramz_ild.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Ramz_ild)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.video_check = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.video_check.setFont(font)
        self.video_check.setObjectName("video_check")
        self.verticalLayout.addWidget(self.video_check)
        self.audio_check = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.audio_check.setFont(font)
        self.audio_check.setObjectName("audio_check")
        self.verticalLayout.addWidget(self.audio_check)
        self.link_l = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.link_l.setFont(font)
        self.link_l.setText("")
        self.link_l.setObjectName("link_l")
        self.verticalLayout.addWidget(self.link_l)
        self.down_p = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.down_p.setFont(font)
        self.down_p.setObjectName("down_p")
        self.verticalLayout.addWidget(self.down_p)
        self.down_p.raise_()
        self.label.raise_()
        self.link_l.raise_()
        self.audio_check.raise_()
        self.video_check.raise_()
        Ramz_ild.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ramz_ild)
        QtCore.QMetaObject.connectSlotsByName(Ramz_ild)

    def retranslateUi(self, Ramz_ild):
        _translate = QtCore.QCoreApplication.translate
        Ramz_ild.setWindowTitle(_translate("Ramz_ild", "Ramz_ild"))
        self.label.setText(_translate("Ramz_ild", "Вставьте ссылку и нажмите кнопку скачать"))
        self.video_check.setText(_translate("Ramz_ild", "Видео"))
        self.audio_check.setText(_translate("Ramz_ild", "Только аудио"))
        self.down_p.setText(_translate("Ramz_ild", "Скачать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ramz_ild = QtWidgets.QMainWindow()
    ui = Ui_Ramz_ild()
    ui.setupUi(Ramz_ild)
    Ramz_ild.show()
    sys.exit(app.exec_())
